### ISSUE TITLE
Zoom out fast, image highlights

### ISSUE THREAD

**Issue by sebastian-meier** [cpietsch/vikus-viewer#10]
When zooming out fast, while filtering is active, some of the images in the lower area are not in filter-out-state
![Screenshot 2020-04-23 at 17 10 46](https://user-images.githubusercontent.com/302789/80117736-d216a500-8587-11ea-8e48-9131b0c66601.png)

**Comment by cpietsch** [comment]
I could not reproduce this in the current version. Might be fixed already
