### ISSUE TITLE
Changing tsne sidebar label to "similarity" breaks TSNE view.

### ISSUE THREAD

**Issue by jasonalderman** [cpietsch/vikus-viewer#5]
Hello! 
The latest update that changes "tsne" to "similarity" in the `.navi` sidebar (2e5879c) in `index.html` appears to break the TSNE visualization unless viz.js or canvas.js are modified, since `state.mode` is set using `canvas.setMode()` 

https://github.com/cpietsch/vikus-viewer/blob/2e5879c38c18317ca36404645fda5622c54b7f89/js/canvas.js#L458-L461

with the text of the label...

https://github.com/cpietsch/vikus-viewer/blob/2e5879c38c18317ca36404645fda5622c54b7f89/js/viz.js#L123-L127

...and then referenced directly to determine whether to project TSNE...

https://github.com/cpietsch/vikus-viewer/blob/2e5879c38c18317ca36404645fda5622c54b7f89/js/canvas.js#L660-L661

Would using the button's class (`.button.tsne`, `.button.time`) instead of the text make more sense? Or is it better to just change the `if` statement on line 660 of canvas.js?
(Or am I missing something else here? Figuring out Vikus for the first time!)

**Comment by cpietsch** [comment]
Hey @jasonalderman, thanks for report!
Using the div text is indeed not so clever. I changed it to a data attribute.
